apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aiops.aiops.geektime.com
spec:
  group: aiops.geektime.com
  names:
    kind: AIOps
    plural: aiops
    singular: aiops
    shortNames:
      - aiops
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                domain:
                  type: string
                  description: expert's domain
            status:
              type: object