apiVersion: batch/v1
kind: Job
metadata:
  name: seed-data
  annotations:
    "helm.sh/hook": pre-install
  labels:
    app: seed-data
    hook-type: pre-install
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: ghcr.io/groundnuty/k8s-wait-for:v2.0
          args: ["pod", "-lapp=vote"]    
      containers:
        - name: seed-data
          image: "{{ .Values.seed.image }}:{{ .Values.seed.tag }}"
          command: ["sh", "-c", "echo 'Running pre-install job...'"]
      restartPolicy: Never  # 任务完成后不重启 Pod
  backoffLimit: 4  # 最大重试次数，如果 Pod 失败，会重试直到达到这个次数